### ISSUE TITLE
Cluster name in config.yaml and eks-config.yaml must be the same for alb ingress to work

### ISSUE THREAD

**Issue by foot** [weaveworks/wkp-docs#12]
If they're not the same the alb-ingress-ctl will error with:

```
{"level":"error","ts":1619188655.024961,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"wkp-ui-alb-ingress","namespace":"wkp-ui","error":"couldn't auto-discover subnets: unable to discover at least one subnet"}
```

We could add that error to the docs so its easily searchable? And a note to the Creation w/ EKS config about this gotcha or in the troubleshooting section perhaps.

**Comment by pfcurtis** [comment]
It would be sufficient to note this in the docs and in the config.yaml so it isn't missed.

**Comment by morancj** [comment]
Closing before archiving repo.
